[package]
name = "PhiFont"
version = "0.1.0"
authors = ["Stroxat <strox@weed>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
harfbuzz-sys = "*"
freetype = "0.4.1"
